# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mate Paiva
email: mmccpp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor web e redator web. Em 2014, descobriu na programação uma nova paixão e um novo objetivo de vida: tornar-se desenvolvedor full-stack em JavaScript. Agora equilibra-se entre as humanas e as exatas, passa os dias lendo documentações de linguagens e frameworks e fazendo experiências com códigos para garantir no futuro o título de ninja em todas as pilhas do desenvolvimento: database, server-side, client-side, desktop, mobile... e onde mais a web se infiltrar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matepaiva.github.io" # the base hostname & protocol for your site
slogan: "Desenvolvimento web também é coisa de humanas."
blogtitle: "Meus Projetos"
permalink: /projetos/:title/
twitter_username:     matepaiva
github_username:      matepaiva
linkedin_address: https://br.linkedin.com/pub/matheus-paiva/b3/bb7/730

# Build settings
markdown: kramdown

