# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mate Paiva
email: mmccpp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Olar!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matepaiva.github.io" # the base hostname & protocol for your site
slogan: "Desenvolvimento web também é coisa de humanas."
permalink: /blog/:categories/:title/
safe: false
lsi: true
twitter_username:     matepaiva
github_username:      matepaiva
linkedin_username:    matepaiva

# Build settings
markdown: kramdown
collections:
  - projetos

collections:
  projetos:
    name: Meus Projetos
    output: true
    url: /projetos/
  posts:
    name: Blog
    url: /blog/

